shader module and add image res
VulkanTutorialCN/VulkanTutorialCN pull request #3
Opened 2021-05-21 09:56 UTC by SakuragiHnmch

2021-05-21 11:10 UTC, FlyAndNotDown requested changes

2021-05-21 11:10 UTC, FlyAndNotDown commented on docs/03-drawing-a-triangle/03-graphics-pipeline-basics/02-shader-modules.md
> +鉴于这是我们的第一个三角形，我们将不会应用任何变换，仅仅只是直接把标准化设备坐标指定为三个顶点的位置，来创建下面的三角形：
- "鉴于这是我们的第一个三角形，我们将不会应用任何变换，仅仅只是直接把标准化设备坐标指定为三个顶点的位置，来创建下面的三角形：" -> "因为这是我们的第一个三角形，我们先不必把难度弄的太大，我们先不加变换，只是简单地把顶点位置直接输出到标准化设备坐标中，下面是我们的目标："

2021-05-21 11:10 UTC, FlyAndNotDown commented on docs/03-drawing-a-triangle/03-graphics-pipeline-basics/02-shader-modules.md
> +通常来说这些坐标会被存储在一个顶点缓冲里面，但是在Vulkan中创建一个顶点缓冲并将数据填入其中并不是一件简单的事情。所以，我决定延后介绍这部分内容，直到我们满意地看见一个三角形弹出在屏幕上。同时，我们将做一些稍微不太常规的事情：直接把坐标放入顶点着色器中。代码如下：
- "所以，我决定延后介绍这部分内容，直到我们满意地看见一个三角形弹出在屏幕上。" -> "所以，我们稍后再看这部分该怎么做，眼下，我们只需要把注意力放在我们的第一个三角形上即可。"
 - "同时，我们将做一些稍微不太常规的事情：直接把坐标放入顶点着色器中" -> "同时，我们还要做一件有悖常规的事情 —— 把坐标硬编码进着色器中，这样我们可以快速地得到结果。"

2021-05-21 11:10 UTC, FlyAndNotDown commented on docs/03-drawing-a-triangle/03-graphics-pipeline-basics/02-shader-modules.md
> +每个顶点都会调用一次`main`函数。内置变量`gl_VertexIndex`包含了当前顶点的索引。这通常是顶点缓冲区的索引，但在我们的例子中，它将会是硬编码顶点数据数组的索引。每个顶点的位置从着色器的常量数组中取得，通过与伪造的`y`和`w`元素组合，生成了裁剪坐标系中位置。内置变量`gl_Position`作为输出。
润色下

2021-05-21 11:10 UTC, FlyAndNotDown commented on docs/03-drawing-a-triangle/03-graphics-pipeline-basics/02-shader-modules.md
> +顶点着色器输出的位置形成了三角形，而该三角形通过片段(也即像素点)填充了屏幕的一块区域。片段着色器在这些片段上被调用，为帧缓冲区生成颜色和深度。一个为整个三角形输出红色的简单片段着色器代码如下：
- "顶点着色器输出的位置形成了三角形，而该三角形通过片段(也即像素点)填充了屏幕的一块区域。" -> "顶点着色器输出的位置组成了一系列三角形，而三角形会被光栅化成不用的片段（也就是像素点），片段将会一片片地将屏幕填满。"
 - "片段着色器在这些片段上被调用，为帧缓冲区生成颜色和深度。" -> "每一个片段都会经过片段着色器的处理，为帧缓冲生成颜色与深度值。"
 - "一个为整个三角形输出红色的简单片段着色器代码如下：" -> "一个将整个三角形的片段染成红色的片段着色器代码如下："

2021-05-21 11:10 UTC, FlyAndNotDown commented on docs/03-drawing-a-triangle/03-graphics-pipeline-basics/02-shader-modules.md
> +正如每个顶点着色器的`main`函数会为每个顶点调用一样，每个片段着色器的`main`函数也会为每个片段而调用。GLSL中的颜色是一个四元素向量，在[0, 1]的范围内分别代表R、G、B和透明通道。不同于顶点着色器的`gl_Position`，并没有内置变量来为当前的片段输出颜色。你必须为每一个帧缓冲指定你自己的输出变量，`layout(location = 0)`修饰语指定了帧缓冲的索引。红色
润色下

2021-05-21 11:10 UTC, FlyAndNotDown commented on docs/03-drawing-a-triangle/03-graphics-pipeline-basics/02-shader-modules.md
> +让整个三角形都显示红色不是那么有趣，下面的三角形不是看起来更加有意思一些吗？
- "让整个三角形都显示红色不是那么有趣，下面的三角形不是看起来更加有意思一些吗？" -> "不过整个三角形都是红色也显得太无趣了点，让我们来让它变得更有意思一些："

2021-05-21 11:10 UTC, FlyAndNotDown commented on docs/03-drawing-a-triangle/03-graphics-pipeline-basics/02-shader-modules.md
> +输入变量的名字不必和输出变量一样，它们会通过由`location`指示符指定的索引值链接到一起。片段着色器中的`main`函数做了一定的修改，输出的颜色值加上了一个alpha值。如同上面的图片所显示的那样，`fragColor`的值会自动地在三个顶点之间进行插值，形成了一个平滑的梯度。
- "`fragColor`的值会自动地在三个顶点之间进行插值，形成了一个平滑的梯度。" -> "`fragColor` 的值会自动在三个顶点中进行插值，形成有趣的渐变。"

2021-05-21 11:12 UTC, FlyAndNotDown commented
@HitLumino @bluesky013 一起帮忙看看

2021-05-21 16:50 UTC, bluesky013 commented on docs/03-drawing-a-triangle/03-graphics-pipeline-basics/02-shader-modules.md
> +使用字节码格式的一大优势在于，显著地简化了GPU厂商编写的，用于将着色器代码编译为原生代码的编译器。过去的经验表明，对于GLSL这样的人类可读语言，一些GPU厂商对标准的解释相当灵活。如果你碰巧使用其中一家厂商的GPU编写了重要的着色器，那么你将面临其他厂商的驱动程序由于语法错误而拒绝你的代码的风险，或者更糟，你的着色器会由于编译器错误而与预料中的运行不一致。使用像SPIR-V这样简单直接的字节
- “用于将着色器代码编译为原生代码的编译器” 按照SPIR-V spec的定义“SPIR-V is a simple binary intermediate language”，是否应该翻译为一种二进制中间语言，

2021-05-21 17:03 UTC, bluesky013 commented on docs/03-drawing-a-triangle/03-graphics-pipeline-basics/02-shader-modules.md
> +顶点着色器处理每一个即将到来的顶点。它将顶点的属性，诸如世界坐标、颜色、法线还有纹理坐标，作为输入。裁剪坐标系中的最终位置，需要传给片段着色器的属性(颜色和纹理坐标)则作为输出。然后，这些值将会被光栅器插值到片段中，以生成一个平滑的梯度。
- “然后，这些值将会被光栅器插值到片段中，以生成一个平滑的梯度。” rasterizer我觉得不应该强翻译成光栅化器，是否这样会更好点：这些值会在光栅化时在片元之间平滑插值。

2021-05-21 17:09 UTC, bluesky013 commented on docs/03-drawing-a-triangle/03-graphics-pipeline-basics/02-shader-modules.md
> +*裁剪坐标*(*clip coordinate*)是由顶点着色器输出的具有四个维度的向量，随后把整个向量除以向量的最后一个元素可以得到*标准化设备坐标*(*normalized device coordinate*)。标准化设备坐标属于[齐次坐标](https://en.wikipedia.org/wiki/Homogeneous_coordinates)(*homogeneous coordi
- "将帧缓冲区映射到..." 是否考虑“视口坐标系”，我理解最终的坐标取决于viewport而不是framebuffer的大小。

2021-05-21 17:16 UTC, bluesky013 commented on docs/03-drawing-a-triangle/03-graphics-pipeline-basics/02-shader-modules.md
> +正如每个顶点着色器的`main`函数会为每个顶点调用一样，每个片段着色器的`main`函数也会为每个片段而调用。GLSL中的颜色是一个四元素向量，在[0, 1]的范围内分别代表R、G、B和透明通道。不同于顶点着色器的`gl_Position`，并没有内置变量来为当前的片段输出颜色。你必须为每一个帧缓冲指定你自己的输出变量，`layout(location = 0)`修饰语指定了帧缓冲的索引。红色
- layout 修饰语->限定符
- "红色被写入了这个`outColor`变量，这个变量与索引为`0`的第一个(也是唯一的一个)帧缓冲链接到一起。"  -> ”红色值通过outColor写入帧缓冲的第0个渲染目标(在此例中仅1个)"

2021-05-21 17:20 UTC, bluesky013 commented on docs/03-drawing-a-triangle/03-graphics-pipeline-basics/02-shader-modules.md
> +输入变量的名字不必和输出变量一样，它们会通过由`location`指示符指定的索引值链接到一起。片段着色器中的`main`函数做了一定的修改，输出的颜色值加上了一个alpha值。如同上面的图片所显示的那样，`fragColor`的值会自动地在三个顶点之间进行插值，形成了一个平滑的梯度。
- `fragColor`的值会自动地在三角形图元的三个顶点之间进行(重心)插值，形成了一个平滑的梯度。

2021-05-21 18:43 UTC, HitLumino reviewed
翻译真心不容易啊

2021-05-21 18:43 UTC, HitLumino commented on docs/03-drawing-a-triangle/03-graphics-pipeline-basics/02-shader-modules.md
> +通常来说这些坐标会被存储在一个顶点缓冲里面，但是在Vulkan中创建一个顶点缓冲并将数据填入其中并不是一件简单的事情。所以，我决定延后介绍这部分内容，直到我们满意地看见一个三角形弹出在屏幕上。同时，我们将做一些稍微不太常规的事情：直接把坐标放入顶点着色器中。代码如下：
“这些坐标”上下文读下来不明确，应该改为这些顶点数据会先存储在顶点缓冲里，顶点着色器再从顶点缓冲中读取顶点数据。

2021-05-21 18:43 UTC, HitLumino commented on docs/03-drawing-a-triangle/03-graphics-pipeline-basics/02-shader-modules.md
> +*裁剪坐标*(*clip coordinate*)是由顶点着色器输出的具有四个维度的向量，随后把整个向量除以向量的最后一个元素可以得到*标准化设备坐标*(*normalized device coordinate*)。标准化设备坐标属于[齐次坐标](https://en.wikipedia.org/wiki/Homogeneous_coordinates)(*homogeneous coordi
These normalized device coordinates are homogeneous coordinates that map the framebuffer to a [-1, 1] by [-1, 1].
这里的坐标[-1, 1] by [-1, 1]应该说的不是标准化设备坐标，NDC此时应该还是3维，经过视口变换之后变成屏幕坐标才是2维。我觉得 @bluesky013 说的对，这里“map”应该是加了视口变换。

2021-05-21 18:43 UTC, HitLumino commented on docs/03-drawing-a-triangle/03-graphics-pipeline-basics/02-shader-modules.md
> +如果你之前接触过计算机图形学，那么你应该已经熟悉了这些内容。如果你之前使用过OpenGL，你将会发现，Y坐标的符号翻转了过来。而Z坐标则使用和Direct3D相同的取值范围，从0到1。
这里的坐标是只屏幕坐标吧，我看完这段话我是蒙了。。。都是0-1，只是方向不同罢了。Vulkan 和 DX 屏幕空间原点是左上，OpenGL是左下。所以OpenGL的Y需要翻转。那既然是屏幕空间为啥还有Z???(在NDC下，Vulkan 和DX确实是Z一样，但不是一个手系)（PS:我百度了）所以，我建议“而 Z 轴的取值范围却又与 Direct3D 一致(从 0 到 1)"去掉。着重解释一下翻转即可。

2021-05-21 18:43 UTC, HitLumino commented on docs/03-drawing-a-triangle/03-graphics-pipeline-basics/02-shader-modules.md
> +如果你之前接触过计算机图形学，那么你应该已经熟悉了这些内容。如果你之前使用过OpenGL，你将会发现，Y坐标的符号翻转了过来。而Z坐标则使用和Direct3D相同的取值范围，从0到1。
DirectX/Metal:

NDC Y+ up
FrameBuffer Y+ down
OpenGL:

NDC Y+ up
FrameBuffer Y+ up
Vulkan:

NDC Y+ down
FrameBuffer Y+ down

2021-05-22 01:35 UTC, SakuragiHnmch commented
感谢各位大佬指正=  =

2021-05-22 01:50 UTC, SakuragiHnmch commented on docs/03-drawing-a-triangle/03-graphics-pipeline-basics/02-shader-modules.md
> +使用字节码格式的一大优势在于，显著地简化了GPU厂商编写的，用于将着色器代码编译为原生代码的编译器。过去的经验表明，对于GLSL这样的人类可读语言，一些GPU厂商对标准的解释相当灵活。如果你碰巧使用其中一家厂商的GPU编写了重要的着色器，那么你将面临其他厂商的驱动程序由于语法错误而拒绝你的代码的风险，或者更糟，你的着色器会由于编译器错误而与预料中的运行不一致。使用像SPIR-V这样简单直接的字节
emmmm，KHRONOS的编译器把着色器代码编译成SPIR-V，GPU供应商的编译器应该是把着色器代码编译成可以在GPU上执行的指令吧= =，不过翻成原生代码确实不太好，我不太了解着色器语言在一般GPU的编译过程。

2021-05-22 02:01 UTC, SakuragiHnmch commented on docs/03-drawing-a-triangle/03-graphics-pipeline-basics/02-shader-modules.md
> +然而，这并不意味着我们需要手动编写二进制字节码。Khronos发布了自己的独立于GPU厂商的编译器，用于将GLSL编译为SPIR-V。编译器用于验证着色器代码是否完全符合标准，并生成一个可传入程序的SPIR-V二进制文件。你可以在程序运行时将编译器作为一个库来生成SPIR-V文件，但是我们在本教程中不会这么做。虽然我们可以通过`glslagvalidator.exe`直接使用编译器，但我们将通过
"来生成SPIR-V文件" -> "来编译 SPIR-V文件"  -----这一句应该是编译源码然后生成SPIR-V吧，直接说编译SPIR-V感觉不太对

2021-05-22 03:02 UTC, SakuragiHnmch commented on docs/03-drawing-a-triangle/03-graphics-pipeline-basics/02-shader-modules.md
> +使用字节码格式的一大优势在于，显著地简化了GPU厂商编写的，用于将着色器代码编译为原生代码的编译器。过去的经验表明，对于GLSL这样的人类可读语言，一些GPU厂商对标准的解释相当灵活。如果你碰巧使用其中一家厂商的GPU编写了重要的着色器，那么你将面临其他厂商的驱动程序由于语法错误而拒绝你的代码的风险，或者更糟，你的着色器会由于编译器错误而与预料中的运行不一致。使用像SPIR-V这样简单直接的字节
Khronos的编译器会把glsl编译成SPIR-V，但是一般GPU厂商的编译器会把着色器代码编译成能够执行的二进制指令吧= =，不过翻译原生代码确实不太合理。

2021-05-24 16:25 UTC, FlyAndNotDown approved these changes

2021-05-24 16:27 UTC, merged

2021-05-24 16:27 UTC, FlyAndNotDown commented
@SakuragiHnmch 我先给你合入了，图片先上库，翻译完这节后半部分我们再一起校对一遍